-- Seed generato da scripts/build-seed.py (dati veri, snapshot 28/8/2026)
begin;

-- Agenti
insert into agents (slug,name,role,tagline,avatar,schedule_label,cron,color,sort) values ('capo','CAPO','Direttore operativo','Orchestra la squadra, aggrega i numeri, decide sui dati.','/avatars/capo.png','Report mattina e sera',null,'#0E7C6B',0) on conflict (slug) do update set name=excluded.name, role=excluded.role, tagline=excluded.tagline, avatar=excluded.avatar, schedule_label=excluded.schedule_label, cron=excluded.cron, color=excluded.color, sort=excluded.sort;
insert into agents (slug,name,role,tagline,avatar,schedule_label,cron,color,sort) values ('scout','RIVO - SCOUT','Talent scout creator','Scansiona largo, tiene solo i perfetti. Trova creator travel IT.','/avatars/scout.png','Ogni mattina alle 6:00','0 4 * * *','#B07A2A',1) on conflict (slug) do update set name=excluded.name, role=excluded.role, tagline=excluded.tagline, avatar=excluded.avatar, schedule_label=excluded.schedule_label, cron=excluded.cron, color=excluded.color, sort=excluded.sort;
insert into agents (slug,name,role,tagline,avatar,schedule_label,cron,color,sort) values ('ig_email','RIVO - IG e Email','Risponditore DM + Email','Il clone di Valerio: risposte, primi contatti, bozze da approvare.','/avatars/ig_email.png','Ogni ora, 8:15-20:15','15 6-18 * * *','#C24E6B',2) on conflict (slug) do update set name=excluded.name, role=excluded.role, tagline=excluded.tagline, avatar=excluded.avatar, schedule_label=excluded.schedule_label, cron=excluded.cron, color=excluded.color, sort=excluded.sort;
insert into agents (slug,name,role,tagline,avatar,schedule_label,cron,color,sort) values ('reddit','RIVO - REDDIT','Community builder','Aiuto vero su Reddit, karma e autorita EU261. Mai spam.','/avatars/reddit.png','Ogni ora, 8:00-20:00','0 6-18 * * *','#D4552F',3) on conflict (slug) do update set name=excluded.name, role=excluded.role, tagline=excluded.tagline, avatar=excluded.avatar, schedule_label=excluded.schedule_label, cron=excluded.cron, color=excluded.color, sort=excluded.sort;

-- Creator (CRM completa)
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Vanessa Russo Vidali','vanessarussovidali','sì (Linktree)','8,9k','Micro','Call fissata','Email','vanessarussovidali@gmail.com','Call fissata ven 28/8 ore 9:00 su Meet. Calda, slow travel.','Bassa','https://www.instagram.com/vanessarussovidali/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Trolleygirl','trolleygirl_','trolleygirl.it',null,null,'Call fissata','DM','trolleygirl.viaggi@gmail.com','Call fissata ven 28/8 ore 16:30 (DM). Molto calda, competitor insoddisfatto. Punti forti: dashboard + bonifico 15gg.','Alta','https://www.instagram.com/trolleygirl_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Julian Vigato','perdersi_altrove','julian.perdersi_altrove','84,6k','Mid','Call fissata','Email','perdersialtrove@gmail.com','Call fissata ven 28/8 ore 17:00. Link Meet inviato 27/8. Performance puro.','Media','https://www.instagram.com/perdersi_altrove/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Filippo Quitadamo','filoquita','filo.quita','171k','Big','Risposto','Email','filoquita.travel@gmail.com','Caldissimo, vuole ibrido. Aspetta WhatsApp di Valerio per fissare la call.','Media','https://www.instagram.com/filoquita/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Giada & Loris','lostandfoundtravelling',null,'169k','Big','Risposto','Email','lostandfoundtravelling@gmail.com','Email ibrido inviata 26/8. In attesa di idea creativa + fee. Decisione 700 euro parcheggiata.','Alta','https://www.instagram.com/lostandfoundtravelling/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('gpintrip_ (Gire & Giulia)','gpintrip_','gpintrip',null,null,'Risposto','DM',null,'Molto caldi, vogliono i numeri per iscritto: aspettiamo la loro email.','Alta','https://www.instagram.com/gpintrip_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('2romanintrip','2romanintrip',null,null,null,'Risposto','DM',null,'Coppia interessata: ''Spiegaci meglio di cosa si tratta''. Da qualificare e portare in call.',null,'https://www.instagram.com/2romanintrip/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('simonemariiino','simonemariiino',null,null,null,'Risposto','DM',null,'Interessato, vuole dettagli (contenuti, compenso, tempistiche). Portare in call.',null,'https://www.instagram.com/simonemariiino/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Sari','Sari',null,null,null,'Risposto','DM',null,'''Dammi pure piu informazioni.'' Interessata, portare in call.',null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Sarah Vilasi Ammirato','Sarah Vilasi Ammirato',null,null,null,'Risposto','DM',null,'''Mi piacerebbe saperne di piu.'' Interessata, portare in call.',null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('yass.viaggi','yass.viaggi',null,null,null,'Risposto','DM',null,'Interessato, in linea col travel. Vuole struttura, contenuti, compenso.',null,'https://www.instagram.com/yass.viaggi/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Nicoló Dossi','nicodossi_',null,'64,6k','Mid','Risposto','Email','nicodossi01@gmail.com','Email 26/8 con 40% esplicito. In attesa disponibilita per la call.','Media','https://www.instagram.com/nicodossi_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Albi & Fede','albiefede',null,'33,4k','Micro','Risposto','Email','195eoltre@gmail.com','Proposti slot mer 26 o gio 27. In attesa risposta.','Media','https://www.instagram.com/albiefede/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('aalessiadefazio','aalessiadefazio',null,null,null,'Risposto','DM','alessiadefazio.collab@gmail.com','Email ibrido inviata 26/8 con proposta call. In attesa.',null,'https://www.instagram.com/aalessiadefazio/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Cristian Zambrini','Cristian Zambrini',null,null,null,'Risposto','DM',null,'Aveva frainteso, chiarito via DM. In attesa risposta, prossimo step call.',null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('viaggio.ideale','viaggio.ideale',null,null,null,'Risposto','DM','viaggio.ideale@gmail.com','Fisso-oriented, manda il media kit. Poi reframe + call.',null,'https://www.instagram.com/viaggio.ideale/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('lorenzopabloo','lorenzopabloo',null,null,null,'Risposto','DM',null,'Interessato ma in viaggio: ricontattare a settembre. Parcheggiato.',null,'https://www.instagram.com/lorenzopabloo/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('travelin.yellow','travelin.yellow',null,null,null,'Risposto','DM',null,'No gentile: lavorano solo con quota fissa. Decisione mini-ibrido in sospeso.',null,'https://www.instagram.com/travelin.yellow/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Jess | Travel Creator','Jess | Travel Creator',null,null,null,'Risposto','DM',null,'Soft no: collab recente con servizio simile. Porta aperta.',null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Andrea Petroni','Andrea Petroni',null,null,null,'Risposto','DM','andrea.petroni@bang.it','Rimanda alla sua agenzia (vologratis). Bassa priorita per performance.','Bassa',null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Michela d''Ario','micmalditravel',null,'94,5k','Mid','Risposto','Email','midario78@gmail.com','Chiusura gentile 25/8: lavora solo a fee fissa. Porta aperta al performance.','Media','https://www.instagram.com/micmalditravel/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Vincent Ascione & Claudia Russo','littletravelsbiglove',null,'382k','Big','Contattato','Email','vinecloditeam@gmail.com','Follow-up gentile 26/8. In attesa.','Alta','https://www.instagram.com/littletravelsbiglove/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Leonardo Bellizzi','leonardbells',null,'216k','Big','Contattato','Email','Leonardbells.business@gmail.com','Follow-up gentile 26/8. In attesa.','Alta','https://www.instagram.com/leonardbells/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Aurora Marzari','aurorainviaggio',null,'30,6k','Micro','Contattato','Email','aurorainviaggio@gmail.com','Follow-up gentile 26/8 (viaggi di gruppo). In attesa.','Alta','https://www.instagram.com/aurorainviaggio/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Marina','_marilix_',null,'14,9k','Micro','Contattato','Email','marilix.collab@gmail.com','Follow-up gentile 26/8 (borghi/voli). In attesa.','Bassa','https://www.instagram.com/_marilix_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Matteo Lazzarini','_lazzarinimatteo_',null,'23,9k','Micro','Contattato','Email','Matteolazzarinibusiness@gmail.com','Follow-up gentile 26/8 (expat/voli). In attesa.','Media','https://www.instagram.com/_lazzarinimatteo_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('complici.avventure','complici.avventure',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/complici.avventure/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('wheregiadagoes','wheregiadagoes',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/wheregiadagoes/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Alessio Molla','Alessio Molla',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Legalmente scorretto','Legalmente scorretto',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Teresa','Teresa',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('world_mappers','world_mappers',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/world_mappers/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('viaggiapiudiprima','viaggiapiudiprima',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/viaggiapiudiprima/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('vologratis','vologratis',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/vologratis/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Giulia | Nomade Digitale','Giulia | Nomade Digitale',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('karimigno','karimigno',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/karimigno/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Massimiliano Dona','Massimiliano Dona',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('fedeontravel','fedeontravel',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/fedeontravel/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('portamiavedere','portamiavedere',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/portamiavedere/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Ewa | Travel Creator | Marche','Ewa | Travel Creator | Marche',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Federica Xotti','Federica Xotti',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('grattalamappa','grattalamappa',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/grattalamappa/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('martadimuro_','martadimuro_',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/martadimuro_/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Simona C. | travel dreamer','Simona C. | travel dreamer',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Marella Bagnoli','Marella Bagnoli',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Flavio Di Leo','Flavio Di Leo',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('viaggiandopermano','viaggiandopermano',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/viaggiandopermano/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('antonellamarteddu92','antonellamarteddu92',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/antonellamarteddu92/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Franci Confalonieri','Franci Confalonieri',null,null,null,'Contattato','DM',null,null,null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('asfarasyoucan_travel','asfarasyoucan_travel',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/asfarasyoucan_travel/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('viaggiasenzanalira','viaggiasenzanalira',null,null,null,'Contattato','DM',null,null,null,'https://www.instagram.com/viaggiasenzanalira/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('dreamersinviaggio','dreamersinviaggio',null,null,null,'Contattato','DM',null,'Ha solo visualizzato, nessuna risposta.',null,'https://www.instagram.com/dreamersinviaggio/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Giusi Casada','giusicasada',null,'276k','Big','Scartato','Email','giuseppinacasada@gmail.com','No gentile per coerenza (paesaggi/mare, non voli). Chiusa con email amichevole. Porta aperta.','Alta','https://www.instagram.com/giusicasada/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('annina_travel','annina_travel',null,null,null,'Scartato','DM',null,'Automazione: risposta bot identica ripetuta. Non un contatto reale.',null,'https://www.instagram.com/annina_travel/','crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();
insert into creators (name,ig,tiktok,followers,fascia,stage,canale,email,esito,priorita,url,source) values ('Flaminia Montani','Flaminia Montani',null,null,null,'Scartato','DM',null,'No educato senza motivo. Nessuna riapertura.',null,null,'crm') on conflict (name) do update set stage=excluded.stage, esito=excluded.esito, email=excluded.email, updated_at=now();

-- Lead Scout interessanti (Pronto / Da arricchire)
insert into creators (name,ig,tiktok,followers,stage,email,esito,url,source) values ('ticketsfor_two','ticketsfor_two',null,'12012','Nuovo',null,'Trovato dallo SCOUT, pronto al primo contatto.','https://www.instagram.com/ticketsfor_two/','scout') on conflict (name) do nothing;
insert into creators (name,ig,tiktok,followers,stage,email,esito,url,source) values ('travelholicsouls','travelholicsouls',null,'37304','Nuovo',null,'Trovato dallo SCOUT, pronto al primo contatto.','https://www.instagram.com/travelholicsouls/','scout') on conflict (name) do nothing;
insert into creators (name,ig,tiktok,followers,stage,email,esito,url,source) values ('sonia.luisoni','sonia.luisoni',null,'341','Nuovo',null,'In arricchimento.','https://instagram.com/sonia.luisoni','scout') on conflict (name) do nothing;

-- Reddit: contributi pubblicati
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-26','r/amexItaly','comment','Ritardo volo','Spiegazione assicurazione carta vs EU261','p5zme3s','pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-26','r/ViaggiITA','comment','Ho perso la patente in Scozia','Aiuto pratico noleggio/documenti','p5zme3b','pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-26','r/ViaggiITA','comment','Abbigliamento per trekking','Consigli Dolomiti',null,'pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-26','r/CasualIT','comment','Detto piu insulso','Battuta sulle mezze stagioni (karma building)',null,'pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-27','r/ViaggiITA','comment','Giro del mondo','Consigli itinerario','p6886ci','pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-27','r/ViaggiITA','comment','RECORD GO Rental Car','Diritti consumatore autonoleggio','p6888m5','pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-27','r/ViaggiITA','comment','Malpensa departure EES','Tempi non-Schengen + EES','p69fwof','pubblicato');
insert into reddit_items (date,subreddit,kind,title,body_summary,permalink_id,status) values ('2026-08-27','r/CasualIT','comment','Compagnie telefoniche','Diritti consumatore: recesso, Corecom/conciliaweb','p69fyr9','pubblicato');

-- KV
insert into kv (key,value) values ('reddit_karma', '4'::jsonb) on conflict (key) do update set value=excluded.value, updated_at=now();
insert into kv (key,value) values ('reddit_account', '"u/Valerio_alieri"'::jsonb) on conflict (key) do nothing;

-- Primo evento nel feed
insert into activity_feed (agent_slug,kind,message) values (null,'success','Mission Control collegata: dati importati da Airtable e Reddit. Da adesso la squadra aggiorna qui in tempo reale.');
commit;
